# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

jobs:

- job: Job1

  steps:
  - script: echo Job 1, Avinash!
    displayName: 'Run a one-line script for Job1'

  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script for job1'

- job: job2
  dependsOn: job1
  steps:
    - script: echo Job2, Avinash
      displayName: One-liner for job2
       
    - script: |
        echo Add other tasks for job2
        echo complete job2
      displayName: Multiline for job2
      
      
      
- job: job3
  dependsOn: job2
 
  steps:
    - script: echo job3, Avinash
      displayName: oneliner for job3
       
    - script: echo job3, second step
      displayName: oneliner 2 for job3
  
- job: job4
  
  steps:
    
    - script: echo Job4 script1, Avinash
      displayName: oneliner1 for job4
    
    - script: echo Job4 script2, Avinash
      displayName: oneliner2 for job 4
  