# Understanding Stages


trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    jobs:
      - job: BuildJob1
        steps:
          - bash: echo First build

  - stage: DevBuild
    dependsOn: Build
    jobs:
      - job: DevBuildJob1
        steps:
          - bash: echo DevBuild Job1 Step1
          - bash: echo DevBuild Job1 Step2
      - job: DevBuildJob2
        steps:
          - bash: echo Devbuild Job2 Step1

  - stage: QABuild
    dependsOn: Build
    jobs:
      - job: QABuildJob1
        steps:
          - bash: echo QABuild Job1 Step1
      - job: DevBuildJob2
        steps:
          - bash: echo QAbuild Job2 Step1

  - stage: ProdBuild
    dependsOn:
      - DevBuild
      - QABuild
    jobs:
      - job: ProdBuildJob1
        steps:
          - bash: echo ProdBuild Job1 Step1
          - bash: echo ProdBuild Job1 Step2
